from base.com.controller import complaint_controller
from base.com.controller import department_controller
from base.com.controller import doctor_controller
from base.com.controller import feedback_controller
from base.com.controller import home_controller
from base.com.controller import login_controller
from base.com.controller import medicalhistory_controller
from base.com.controller import medicalreport_controller
from base.com.controller import prediction_controller
from base.com.controller import slot_controller
from base.com.controller import user_controller
from base.com.controller import appointment_controller